# Generated by Django 5.1.2 on 2025-07-28 16:04

import django.db.models.deletion
import formularios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('publico', models.BooleanField(default=False, verbose_name='Visível sem login?')),
                ('abre_em', models.DateTimeField(blank=True, null=True, verbose_name='Abre em')),
                ('fecha_em', models.DateTimeField(blank=True, null=True, verbose_name='Fecha em')),
                ('limite_resps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de respostas')),
                ('tema_json', models.JSONField(blank=True, default=dict, verbose_name='Tema')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'permissions': [('pode_responder', 'Pode responder formulário'), ('pode_gerenciar', 'Pode gerenciar formulário')],
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('texto_curto', 'Texto curto'), ('paragrafo', 'Parágrafo'), ('multipla', 'Múltipla escolha'), ('checkbox', 'Caixas de seleção'), ('lista', 'Lista suspensa'), ('escala', 'Escala 1‑5'), ('data', 'Data'), ('hora', 'Hora'), ('arquivo', 'Upload de arquivo')], max_length=20, verbose_name='Tipo')),
                ('rotulo', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('ajuda', models.CharField(blank=True, max_length=255, verbose_name='Texto de ajuda')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('validacao_json', models.JSONField(blank=True, default=dict, verbose_name='Validação')),
                ('logica_json', models.JSONField(blank=True, default=dict, verbose_name='Lógica condicional')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formularios.formulario')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='OpçãoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='formularios.campo')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rascunho', models.BooleanField(default=False)),
                ('versao_form', models.PositiveIntegerField()),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_formularios', to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios.formulario')),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='ValorResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_arquivo', models.FileField(blank=True, null=True, upload_to=formularios.models.upload_para)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.campo')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='formularios.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_editar', models.BooleanField(default=True)),
                ('pode_ver', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='formularios.formulario')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'unique_together': {('formulario', 'usuario')},
            },
        ),
    ]
