# Generated by Django 5.1.2 on 2025-07-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpçãoCampo',
            new_name='OpcaoCampo',
        ),
    ]
