# Generated by Django 5.1.2 on 2025-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_rename_opçãocampo_opcaocampo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='aceita_respostas',
            field=models.BooleanField(default=True, verbose_name='Aceitando respostas?'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto_curto', 'Texto curto'), ('paragrafo', 'Parágrafo'), ('multipla', 'Múltipla escolha'), ('checkbox', 'Caixas de seleção'), ('lista', 'Lista suspensa'), ('escala', 'Escala 1-5'), ('data', 'Data'), ('hora', 'Hora'), ('arquivo', 'Upload de arquivo')], max_length=20, verbose_name='Tipo'),
        ),
    ]
