# Generated by Django 5.1.2 on 2025-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_formulario_aceita_respostas_alter_campo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='aparece_home',
            field=models.BooleanField(default=False, verbose_name='Aparece na home (popup)?'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='coletar_nome',
            field=models.BooleanField(default=False, verbose_name='Coletar o nome do usuário?'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='nome_coletado',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome (informado no envio)'),
        ),
    ]
