# Generated by Django 5.1.2 on 2025-08-15 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_formulario_aparece_home_formulario_coletar_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='aparece_home',
        ),
        migrations.AddField(
            model_name='formulario',
            name='aparece_na_home',
            field=models.BooleanField(default=False, verbose_name='Aparece na home?'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='quem_responde',
            field=models.CharField(choices=[('100', '100% dos usuários a cada disparo'), ('50', '50% dos usuários alternando por disparo'), ('SEL', 'Selecionar usuários manualmente')], default='100', max_length=3, verbose_name='Quem vai responder'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='repetir_cada',
            field=models.DurationField(blank=True, null=True, verbose_name='Repetir a cada'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='respondentes',
            field=models.ManyToManyField(blank=True, related_name='formularios_alvo', to=settings.AUTH_USER_MODEL, verbose_name='Usuários selecionados (modo manual)'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome_coletado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
