# Generated by Django 5.1.2 on 2025-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_remove_formulario_aparece_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='aparece_na_home',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='quem_responde',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='repetir_cada',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='respondentes',
        ),
        migrations.AddField(
            model_name='formulario',
            name='aparece_home',
            field=models.BooleanField(default=False, verbose_name='Aparece na home (popup)?'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome_coletado',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome (informado no envio)'),
        ),
    ]
