# Generated by Django 5.1.2 on 2025-08-15 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_remove_formulario_aparece_na_home_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='alvo_resposta',
            field=models.CharField(blank=True, choices=[('100', '100%'), ('050', '50%'), ('MAN', 'Selecionar usuários manualmente')], default='100', max_length=3, verbose_name='Quem vai responder'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='alvo_usuarios',
            field=models.ManyToManyField(blank=True, related_name='formularios_alvo', to=settings.AUTH_USER_MODEL, verbose_name='Usuários selecionados (manual)'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='repetir_cada',
            field=models.DurationField(blank=True, null=True, verbose_name='Repetir a cada'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='aparece_home',
            field=models.BooleanField(default=False, verbose_name='Aparece na home?'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome_coletado',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome (informado)'),
        ),
    ]
