# Generated by Django 5.1.2 on 2025-08-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_formulario_alvo_resposta_formulario_alvo_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='valorresposta',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formularios.campo'),
        ),
    ]
