# Generated by Django 5.1.2 on 2025-08-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_campo_arquivado_em_campo_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='arquivado_em',
        ),
        migrations.AlterField(
            model_name='valorresposta',
            name='campo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formularios.campo'),
            preserve_default=False,
        ),
    ]
