# Generated by Django 5.1.2 on 2025-08-20 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_remove_campo_arquivado_em_alter_valorresposta_campo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('EDT', 'Editor'), ('VER', 'Ver respostas')], max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='formularios.formulario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_compartilhados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compartilhamento de formulário',
                'verbose_name_plural': 'Compartilhamentos de formulários',
                'unique_together': {('formulario', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
