# Generated by Django 5.1.2 on 2025-08-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_colaborador_delete_formulariopermissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_responder', 'Pode responder formulário'), ('pode_gerenciar', 'Pode gerenciar formulário'), ('listar_meus', 'Listar meus formulários'), ('criar_formulario', 'Criar formulário')], 'verbose_name': 'formulário', 'verbose_name_plural': 'formulários'},
        ),
    ]
