# Generated by Django 5.1.2 on 2025-08-30 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0013_alter_campo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='formularios.formulario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'formulario'], name='formularios_usuario_df7352_idx')],
                'unique_together': {('formulario', 'usuario')},
            },
        ),
    ]
