# Generated by Django 5.1.2 on 2025-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0014_formulariouserstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='fonte_cfg',
            field=models.JSONField(blank=True, default=dict, verbose_name='Config. da fonte'),
        ),
        migrations.AddField(
            model_name='campo',
            name='fonte_opcoes',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('sqlhub', 'SQL Hub')], default='manual', max_length=12, verbose_name='Fonte das opções'),
        ),
    ]
