# Generated by Django 5.1.2 on 2025-09-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_campo_fonte_cfg_campo_fonte_opcoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='fonte_cfg',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='fonte_opcoes',
        ),
    ]
