# Generated by Django 5.1.2 on 2025-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0016_remove_campo_fonte_cfg_remove_campo_fonte_opcoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='fonte_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Config. da origem (SQLHub)'),
        ),
        migrations.AddField(
            model_name='campo',
            name='origem_opcoes',
            field=models.CharField(choices=[('estatico', 'Opções estáticas'), ('sqlhub', 'Consulta do SQL Hub')], default='estatico', max_length=10, verbose_name='Origem das opções'),
        ),
    ]
