# Generated by Django 5.1.2 on 2025-09-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0017_campo_fonte_json_campo_origem_opcoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='fonte_json',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='origem_opcoes',
        ),
    ]
