# Generated by Django 5.1.2 on 2025-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0018_remove_campo_fonte_json_remove_campo_origem_opcoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='origem_opcoes',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('sqlhub', 'SQLHub')], default='manual', max_length=12),
        ),
        migrations.AddField(
            model_name='campo',
            name='sqlhub_label_field',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='campo',
            name='sqlhub_query_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='sqlhub_value_field',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
