# Generated by Django 5.1.2 on 2025-09-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0019_campo_origem_opcoes_campo_sqlhub_label_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='origem_opcoes',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='sqlhub_label_field',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='sqlhub_query_id',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='sqlhub_value_field',
        ),
    ]
