# Generated by Django 5.1.2 on 2025-09-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0020_remove_campo_origem_opcoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_gerenciar', 'Pode gerenciar formulário'), ('listar_meus', 'Listar meus formulários'), ('criar_formulario', 'Criar formulário')], 'verbose_name': 'formulário', 'verbose_name_plural': 'formulários'},
        ),
    ]
