# Generated by Django 5.1.2 on 2025-09-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0023_alter_formulario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_gerenciar', 'Pode gerenciar formulário'), ('listar_meus', 'Listar meus formulários'), ('pode_criar', 'Criar formulário'), ('criar_formulario', 'Criar formulário'), ('pode_excluir_formulario', 'Pode excluir formulário'), ('pode_excluir_respostas', 'Pode excluir respostas')], 'verbose_name': 'formulário', 'verbose_name_plural': 'formulários'},
        ),
    ]
