# Generated by Django 5.1.2 on 2025-09-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0025_alter_formulario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da seção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('regras_json', models.JSONField(blank=True, default=dict, verbose_name='Regras de visibilidade')),
                ('ativo', models.BooleanField(default=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='formularios.formulario')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['ordem', 'id'],
                'unique_together': {('formulario', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos', to='formularios.secao', verbose_name='Seção'),
        ),
    ]
