# Generated by Django 5.1.2 on 2025-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0026_secao_campo_secao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='secao',
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto_curto', 'Texto curto'), ('paragrafo', 'Parágrafo'), ('multipla', 'Múltipla escolha'), ('checkbox', 'Caixas de seleção'), ('lista', 'Lista suspensa'), ('escala', 'Escala 1-10'), ('data', 'Data'), ('hora', 'Hora'), ('arquivo', 'Upload de arquivo'), ('secao', 'Seção')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Secao',
        ),
    ]
