# Generated by Django 5.1.2 on 2025-09-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0027_remove_campo_secao_alter_campo_tipo_delete_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto_curto', 'Texto curto'), ('paragrafo', 'Parágrafo'), ('multipla', 'Múltipla escolha'), ('checkbox', 'Caixas de seleção'), ('lista', 'Lista suspensa'), ('escala', 'Escala 1-10'), ('data', 'Data'), ('hora', 'Hora'), ('arquivo', 'Upload de arquivo')], max_length=20, verbose_name='Tipo'),
        ),
    ]
