# Generated by Django 5.1.2 on 2024-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_alter_documento_options_documento_analista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='aprovado_por_aprovador2',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='aprovador2',
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('aguardando_analise', 'Aguardando Análise'), ('analise_concluida', 'Análise Concluída'), ('aguardando_elaborador', 'Aguardando Aprovação do Elaborador'), ('aguardando_aprovador1', 'Aguardando Aprovação do Aprovador'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='aguardando_analise', max_length=30),
        ),
    ]
