# Generated by Django 5.1.2 on 2024-11-07 11:57

import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_remove_documento_aprovado_por_aprovador2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=documentos.models.OverwriteStorage(), upload_to=documentos.models.pdf_upload_path),
        ),
    ]
