# Generated by Django 5.1.2 on 2024-11-12 16:55

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_alter_documento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='bloqueada',
            field=models.BooleanField(default=False, help_text='Marque se esta categoria deve bloquear download e impressão dos documentos.'),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_pdf_protected',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/pdf/', location='C:\\Users\\matheus.oliveira\\Desktop\\Portal_Rotoplastyc\\protected_media\\pdf'), upload_to=documentos.models.pdf_upload_path),
        ),
    ]
