# Generated by Django 5.1.2 on 2024-11-12 17:16

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0014_categoria_bloqueada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='documento_pdf_protected',
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/pdf/', location='C:\\Users\\matheus.oliveira\\Desktop\\Portal_Rotoplastyc\\protected_media\\pdf'), upload_to=documentos.models.pdf_upload_path),
        ),
    ]
