# Generated by Django 5.1.2 on 2024-11-12 18:03

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_remove_documento_documento_pdf_protected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\matheus.oliveira\\Desktop\\Portal_Rotoplastyc\\media\\documentos\\pdf'), upload_to=documentos.models.pdf_upload_path),
        ),
    ]
