# Generated by Django 5.1.2 on 2024-11-13 20:21

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_alter_documento_documento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\matheus.oliveira\\Desktop\\Portal_Rotoplastyc\\media'), upload_to=documentos.models.pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('aguardando_analise', 'Aguardando Análise'), ('analise_concluida', 'A análise Concluída'), ('aguardando_elaborador', 'Aguardando Aprovação do Elaborador'), ('aguardando_aprovador1', 'Aguardando Aprovação do Aprovador'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='aguardando_analise', max_length=30),
        ),
    ]
