# Generated by Django 5.1.2 on 2024-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_alter_documento_documento_pdf_alter_documento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('aguardando_analise', 'Aguardando Análise'), ('analise_concluida', 'Análise Concluída'), ('aguardando_elaborador', 'Aguardando Aprovação do Elaborador'), ('aguardando_aprovador1', 'Aguardando Aprovação do Aprovador'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='aguardando_analise', max_length=30),
        ),
    ]
