# Generated by Django 5.1.2 on 2024-11-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0019_alter_documento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='documentos.documento'),
        ),
    ]
