# Generated by Django 5.1.2 on 2024-11-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0022_alter_documento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'default_permissions': (), 'permissions': [('can_approve', 'Pode aprovar documentos'), ('can_reject', 'Pode reprovar documentos'), ('can_analyze', 'Pode analisar documentos'), ('can_view_editables', 'Pode visualizar documentos editáveis'), ('can_view_revisions', 'Pode visualizar revisões de documentos'), ('add_categoria', 'Adicionar Categoria'), ('view_categoria', 'Lista Categorias'), ('change_categoria', 'Editar Categoria'), ('delete_categoria', 'Deletar Categoria'), ('can_add_documento', 'Adicionar Documento'), ('list_pending_approvals', 'Aprovações Pendentes'), ('view_documentos', 'Listar Documentos'), ('view_acessos_documento', 'Visualizar Acessos Documentos'), ('list_reproaches', 'Lista Reprovações'), ('can_view_editavles', 'Lista Editaveis')]},
        ),
    ]
