# Generated by Django 5.1.2 on 2024-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0025_alter_documento_options_documento_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('spreadsheet', 'Planilha')], default='pdf', help_text='Tipo do documento: PDF ou Planilha.', max_length=20),
        ),
    ]
