# Generated by Django 5.1.2 on 2024-12-12 13:55

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0028_alter_acesso_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/opt/gestao_documentos/media'), upload_to=documentos.models.pdf_upload_path),
        ),
    ]
