# Generated by Django 5.1.2 on 2025-01-16 13:24

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0029_alter_documento_documento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('spreadsheet', 'Planilha'), ('pdf_spreadsheet', 'PDF da Planilha')], default='pdf', help_text='Tipo do documento: PDF ou Planilha.', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/opt/Portal_Rotoplastyc/media'), upload_to=documentos.models.pdf_upload_path),
        ),
    ]
