# Generated by Django 5.1.2 on 2025-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0030_alter_documento_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_analise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_aprovado_aprovador',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_aprovado_elaborador',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
