# Generated by Django 5.1.2 on 2025-05-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0037_alter_documento_options_documento_root_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'default_permissions': (), 'permissions': [('view_documentos', 'Listar Documentos'), ('can_add_documento', 'Adicionar Documento'), ('can_active', 'Pode ativar/inativar documentos'), ('view_acessos_documento', 'Visualizar Acessos Documentos'), ('can_view_revisions', 'Visualizar revisões de Documentos'), ('replace_document', 'Substituir PDF'), ('view_documentos_ina', 'Listar Documentos Inativos'), ('list_pending_approvals', 'Aprovações Pendentes'), ('list_reproaches', 'Lista Reprovações'), ('monitor_documents', 'Monitorar Documentos'), ('delete_documento', 'Deletar Documento'), ('can_approve', 'Pode aprovar documentos'), ('can_analyze', 'Pode analisar documentos'), ('can_view_editables', 'Lista Editáveis'), ('view_categoria', 'Lista Categorias'), ('add_categoria', 'Adicionar Categoria'), ('change_categoria', 'Editar Categoria'), ('delete_categoria', 'Deletar Categoria')]},
        ),
        migrations.RemoveConstraint(
            model_name='documento',
            name='unique_revision_per_root_document',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='root_document',
        ),
        migrations.RemoveField(
            model_name='documentodeletado',
            name='root_document_id_original',
        ),
        migrations.RemoveField(
            model_name='documentodeletado',
            name='root_document_nome_original',
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='documentos.documento'),
        ),
    ]
