# Generated by Django 5.1.2 on 2025-05-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0038_alter_documento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'default_permissions': (), 'ordering': ['nome', '-revisao'], 'permissions': [('view_documentos', 'Listar Documentos'), ('can_add_documento', 'Adicionar Documento'), ('can_active', 'Pode ativar/inativar documentos'), ('view_acessos_documento', 'Visualizar Acessos Documentos'), ('can_view_revisions', 'Visualizar revisões de Documentos'), ('replace_document', 'Substituir PDF'), ('view_documentos_ina', 'Listar Documentos Inativos'), ('list_pending_approvals', 'Aprovações Pendentes'), ('list_reproaches', 'Lista Reprovações'), ('monitor_documents', 'Monitorar Documentos'), ('delete_documento', 'Deletar Documento'), ('can_approve', 'Pode aprovar documentos'), ('can_analyze', 'Pode analisar documentos'), ('can_view_editables', 'Lista Editáveis'), ('view_categoria', 'Lista Categorias'), ('add_categoria', 'Adicionar Categoria'), ('change_categoria', 'Editar Categoria'), ('delete_categoria', 'Deletar Categoria')]},
        ),
        migrations.AddField(
            model_name='documento',
            name='root_document',
            field=models.ForeignKey(blank=True, help_text='Referência ao documento original (primeira revisão) da série.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_revisions_history', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='documentodeletado',
            name='root_document_id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentodeletado',
            name='root_document_nome_original',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_original',
            field=models.ForeignKey(blank=True, help_text='Aponta para a revisão imediatamente anterior desta série.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_imediatas', to='documentos.documento'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('root_document', 'revisao'), name='unique_revision_per_root_document'),
        ),
    ]
