# Generated by Django 5.1.2 on 2025-05-23 13:27

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0042_popular_identificador_raiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='identificador_raiz',
        ),
        migrations.RemoveField(
            model_name='documentodeletado',
            name='identificador_raiz_deletado',
        ),
        migrations.AlterField(
            model_name='documento',
            name='aprovador1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovador1_documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('spreadsheet', 'Planilha'), ('pdf_spreadsheet', 'PDF da Planilha')], default='pdf', help_text='Tipo do documento: PDF ou Planilha.', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to=documentos.models.documento_upload_path),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='documentos.documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o documento está ativo.'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='solicitante',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentodeletado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_deletados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
