# Generated by Django 5.1.2 on 2025-05-23 13:39

import django.core.files.storage
import django.db.models.deletion
import documentos.models
import pathlib
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0043_remove_documento_identificador_raiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'default_permissions': (), 'permissions': [('view_documentos', 'Listar Documentos'), ('can_add_documento', 'Adicionar Documento'), ('can_active', 'Ativar/Inativar Documentos'), ('view_acessos_documento', 'Visualizar Acessos'), ('can_view_revisions', 'Visualizar Revisões'), ('replace_document', 'Substituir PDF'), ('view_documentos_ina', 'Listar Inativos'), ('list_pending_approvals', 'Ver Pendências'), ('list_reproaches', 'Ver Reprovações'), ('monitor_documents', 'Monitorar Documentos'), ('delete_documento', 'Deletar Documento'), ('can_approve', 'Pode aprovar documentos'), ('can_analyze', 'Pode analisar documentos'), ('can_view_editables', 'Listar Editáveis'), ('view_categoria', 'Listar Categorias'), ('add_categoria', 'Adicionar Categoria'), ('change_categoria', 'Editar Categoria'), ('delete_categoria', 'Deletar Categoria')]},
        ),
        migrations.AddField(
            model_name='documento',
            name='codigo',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador fixo que liga todas as revisões de um mesmo documento'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='bloqueada',
            field=models.BooleanField(default=False, help_text='Marque se esta categoria deve bloquear download e impressão.'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento_pdf',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/opt/Portal_Rotoplastyc/media')), upload_to=documentos.models.pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='documento',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se o documento está ativo.'),
        ),
        migrations.CreateModel(
            name='DocumentoNomeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_antigo', models.CharField(max_length=200)),
                ('nome_novo', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_nome', to='documentos.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
