# Generated by Django 5.1.2 on 2025-05-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0045_populate_codigo_revisoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.UUIDField(db_index=True, editable=False, help_text='UUID que liga todas as revisões de um mesmo documento', null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='solicitante',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='text_content',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('codigo', 'revisao'), name='uniq_codigo_revisao'),
        ),
    ]
