# Generated by Django 5.1.2 on 2025-05-27 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=10)),
                ('contrato', models.IntegerField()),
                ('epi', models.CharField(max_length=30)),
                ('codigo_estoque', models.CharField(blank=True, max_length=30, null=True)),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('data_entrega', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('quantidade_entregue', models.PositiveIntegerField(default=0)),
                ('colaborador', models.CharField(blank=True, max_length=120, null=True)),
                ('descricao_epi', models.CharField(blank=True, max_length=120, null=True)),
                ('inserido_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-data_entrega'],
                'unique_together': {('unidade', 'contrato', 'epi', 'lote', 'data_entrega')},
            },
        ),
    ]
