# Generated by Django 5.1.2 on 2025-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
