# Generated by Django 5.1.2 on 2025-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_entregaepi_centro_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='descricao_centro_custo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
