# Generated by Django 5.1.2 on 2025-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_entregaepi_descricao_centro_custo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaepi',
            options={'ordering': ['-data_entrega'], 'verbose_name': 'Entrega de EPI', 'verbose_name_plural': 'Entregas de EPI'},
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='data_baixa_erp',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a baixa no ERP foi registrada.', null=True),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='sequencial_baixa_erp',
            field=models.CharField(blank=True, help_text='Número sequencial da baixa gerado no ERP.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('BAIXADO', 'Baixado no ERP')], default='PENDENTE', help_text='Status da baixa no estoque do ERP.', max_length=10),
        ),
    ]
