# Generated by Django 5.1.2 on 2025-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_alter_entregaepi_options_entregaepi_data_baixa_erp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaepi',
            options={'ordering': ['-data_entrega']},
        ),
        migrations.RemoveField(
            model_name='entregaepi',
            name='data_baixa_erp',
        ),
        migrations.RemoveField(
            model_name='entregaepi',
            name='sequencial_baixa_erp',
        ),
        migrations.RemoveField(
            model_name='entregaepi',
            name='status',
        ),
    ]
