# Generated by Django 5.1.2 on 2025-06-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_alter_entregaepi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='data_baixa_erp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='sequencial_baixa_erp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Baixado', 'Baixado')], default='Pendente', max_length=10),
        ),
    ]
