# Generated by Django 5.1.2 on 2025-06-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_entregaepi_data_baixa_erp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaepi',
            options={'default_permissions': (), 'ordering': ['-data_entrega'], 'permissions': [('delivery_epis', 'Entrega de EPIs')]},
        ),
    ]
