# Generated by Django 5.1.2 on 2024-12-03 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('iframe_code', models.TextField()),
                ('allowed_users', models.ManyToManyField(related_name='bi_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
