# Generated by Django 5.1.2 on 2024-12-03 12:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bireport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Relatório BI', 'verbose_name_plural': 'Relatórios BI'},
        ),
        migrations.RemoveField(
            model_name='bireport',
            name='iframe_code',
        ),
        migrations.AddField(
            model_name='bireport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data e hora de criação do relatório.'),
        ),
        migrations.AddField(
            model_name='bireport',
            name='report_id',
            field=models.CharField(default='default_report_id', help_text='ID único do relatório do Power BI.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bireport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do relatório.'),
        ),
        migrations.AlterField(
            model_name='bireport',
            name='allowed_users',
            field=models.ManyToManyField(help_text='Usuários autorizados a visualizar este relatório.', related_name='bi_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bireport',
            name='title',
            field=models.CharField(help_text='Título do relatório BI.', max_length=200),
        ),
    ]
