# Generated by Django 5.1.2 on 2024-12-03 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0002_alter_bireport_options_remove_bireport_iframe_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bireport',
            options={},
        ),
        migrations.RemoveField(
            model_name='bireport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bireport',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='bireport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bireport',
            name='iframe_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bireport',
            name='allowed_users',
            field=models.ManyToManyField(related_name='bi_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bireport',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
