# Generated by Django 5.1.2 on 2024-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0003_alter_bireport_options_remove_bireport_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bireport',
            name='iframe_code',
        ),
        migrations.AddField(
            model_name='bireport',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
