# Generated by Django 5.1.2 on 2024-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0004_remove_bireport_iframe_code_bireport_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bireport',
            name='link',
        ),
        migrations.AddField(
            model_name='bireport',
            name='embed_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
