# Generated by Django 5.1.2 on 2024-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0005_remove_bireport_link_bireport_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='group_id',
            field=models.CharField(default='dc152d8a-7555-42d7-b53d-fbe1ce0dff28', max_length=100),
        ),
        migrations.AddField(
            model_name='bireport',
            name='report_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
