# Generated by Django 5.1.2 on 2024-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0006_bireport_group_id_bireport_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bireport',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
