# Generated by Django 5.1.2 on 2024-12-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0007_alter_bireport_embed_code'),
    ]

    operations = [
    ]
