# Generated by Django 5.1.2 on 2024-12-04 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0008_add_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bireport',
            name='next_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 19, 8, 19, 329456, tzinfo=datetime.timezone.utc)),
        ),
    ]
