# Generated by Django 5.1.2 on 2024-12-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0009_bireport_last_updated_bireport_next_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bireport',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bireport',
            name='next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
