# Generated by Django 5.1.2 on 2024-12-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0010_alter_bireport_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bireport',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bireport',
            name='next_update',
        ),
    ]
