# Generated by Django 5.1.2 on 2024-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0011_remove_bireport_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bireport',
            name='next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
