# Generated by Django 5.1.2 on 2024-12-06 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0017_remove_userbireportrole_roles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bireport',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='reports', to='bi.birole'),
        ),
        migrations.CreateModel(
            name='UserBIReportRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.bireport')),
                ('roles', models.ManyToManyField(blank=True, to='bi.birole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
