# Generated by Django 5.1.2 on 2024-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0018_birole_bireport_allowed_roles_userbireportrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbireportrole',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='bireport',
            name='allowed_roles',
        ),
        migrations.RemoveField(
            model_name='userbireportrole',
            name='bi_report',
        ),
        migrations.RemoveField(
            model_name='userbireportrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='BIRole',
        ),
        migrations.DeleteModel(
            name='UserBIReportRole',
        ),
    ]
