# Generated by Django 5.1.2 on 2024-12-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0022_biaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biaccess',
            options={'default_permissions': (), 'permissions': [('view_bi', 'Lista geral BI'), ('edit_bi', 'Editar BI'), ('view_access', 'Visualizar Acessos')]},
        ),
    ]
