# Generated by Django 5.1.2 on 2024-12-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0023_alter_biaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bireport',
            options={'default_permissions': ()},
        ),
    ]
