# Generated by Django 5.1.2 on 2024-12-09 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0024_alter_bireport_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bireport',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='bi_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
