# Generated by Django 5.1.2 on 2024-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bi', '0025_alter_bireport_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='bi_reports', to='auth.group'),
        ),
    ]
