# Generated by Django 5.1.2 on 2024-12-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0026_bireport_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bireport',
            name='allowed_groups',
        ),
    ]
