# Generated by Django 5.1.2 on 2024-12-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bi', '0027_remove_bireport_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='bi_reports', to='auth.group'),
        ),
    ]
