# Generated by Django 5.1.2 on 2024-12-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0028_bireport_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Permitir acesso a todos os usuários.'),
        ),
    ]
