# Generated by Django 5.1.2 on 2024-12-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0029_bireport_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bireport',
            name='is_public',
        ),
    ]
