# Generated by Django 5.1.2 on 2024-12-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0030_remove_bireport_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='all_users',
            field=models.BooleanField(default=False),
        ),
    ]
