# Generated by Django 5.1.2 on 2025-07-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0031_bireport_all_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biaccess',
            options={'default_permissions': (), 'permissions': [('view_bi', 'Lista geral BI'), ('edit_bi', 'Editar BI'), ('view_access', 'Visualizar Acessos'), ('permission_report', 'Relatório de permissões de BI')]},
        ),
    ]
