# Generated by Django 5.1.2 on 2025-10-15 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0032_alter_biaccess_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIReportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_state', models.TextField(blank=True, null=True)),
                ('active_page', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_info', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='bi.bireport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bi_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'user'], name='bi_bireport_report__192ac0_idx')],
                'unique_together': {('report', 'user')},
            },
        ),
    ]
