# Generated by Django 5.1.2 on 2025-10-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0033_bireportstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BIReportState',
        ),
    ]
