# Generated by Django 5.1.2 on 2025-10-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0034_delete_bireportstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIUserReportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bi_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.bireport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'bi_report'], name='bi_biuserre_user_id_2cb9b7_idx')],
                'unique_together': {('user', 'bi_report')},
            },
        ),
    ]
