# Generated by Django 5.1.2 on 2025-10-20 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bi', '0035_biuserreportstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BISavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=240, null=True, verbose_name='Descrição')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('share_token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visão Salva',
                'verbose_name_plural': 'Visões Salvas',
                'ordering': ['owner', 'name'],
                'permissions': [('manage_saved_views', 'Gerenciar visões salvas de BI')],
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='biaccess',
            options={'default_permissions': (), 'ordering': ['-accessed_at'], 'permissions': [('view_bi', 'Lista geral BI'), ('edit_bi', 'Editar BI'), ('view_access', 'Visualizar Acessos'), ('permission_report', 'Relatório de permissões de BI')], 'verbose_name': 'Acesso a BI', 'verbose_name_plural': 'Acessos a BI'},
        ),
        migrations.AlterModelOptions(
            name='bireport',
            options={'default_permissions': (), 'verbose_name': 'Relatório BI', 'verbose_name_plural': 'Relatórios BI'},
        ),
        migrations.AlterModelOptions(
            name='biuserreportstate',
            options={'default_permissions': (), 'verbose_name': 'Estado do Relatório por Usuário', 'verbose_name_plural': 'Estados de Relatório por Usuário'},
        ),
        migrations.AddIndex(
            model_name='biaccess',
            index=models.Index(fields=['bi_report', 'user'], name='bi_biaccess_bi_repo_aaf1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='biaccess',
            index=models.Index(fields=['accessed_at'], name='bi_biaccess_accesse_ae47a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bireport',
            index=models.Index(fields=['report_id'], name='bi_bireport_report__50379d_idx'),
        ),
        migrations.AddIndex(
            model_name='bireport',
            index=models.Index(fields=['group_id'], name='bi_bireport_group_i_353d54_idx'),
        ),
        migrations.AddIndex(
            model_name='bireport',
            index=models.Index(fields=['last_updated'], name='bi_bireport_last_up_613b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='biuserreportstate',
            index=models.Index(fields=['updated_at'], name='bi_biuserre_updated_972dcf_idx'),
        ),
        migrations.AddField(
            model_name='bisavedview',
            name='bi_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='bi.bireport'),
        ),
        migrations.AddField(
            model_name='bisavedview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bisavedview',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='saved_views_shared', to='auth.group'),
        ),
        migrations.AddField(
            model_name='bisavedview',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='saved_views_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bisavedview',
            index=models.Index(fields=['bi_report', 'owner'], name='bi_bisavedv_bi_repo_dabcec_idx'),
        ),
        migrations.AddIndex(
            model_name='bisavedview',
            index=models.Index(fields=['owner', 'is_default'], name='bi_bisavedv_owner_i_fa4ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='bisavedview',
            index=models.Index(fields=['updated_at'], name='bi_bisavedv_updated_a70fac_idx'),
        ),
        migrations.AddConstraint(
            model_name='bisavedview',
            constraint=models.UniqueConstraint(fields=('bi_report', 'owner', 'name'), name='uniq_savedview_name_owner_bi'),
        ),
    ]
