# Generated by Django 5.1.2 on 2025-10-21 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bi', '0036_bisavedview_alter_biaccess_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bireport',
            name='pbi_group_id',
            field=models.CharField(blank=True, db_index=True, help_text='GroupId/Workspace (GUID). Se vazio, será herdado de group_id.', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='bireport',
            name='pbi_report_id',
            field=models.CharField(blank=True, db_index=True, help_text='ReportId (GUID). Se vazio, será herdado de report_id.', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='bireport',
            name='upstream_dataflows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='bireport',
            index=models.Index(fields=['pbi_report_id'], name='bi_bireport_pbi_rep_acf55f_idx'),
        ),
        migrations.AddIndex(
            model_name='bireport',
            index=models.Index(fields=['pbi_group_id'], name='bi_bireport_pbi_gro_540fc5_idx'),
        ),
    ]
