# Generated by Django 5.1.2 on 2025-10-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0037_bireport_pbi_group_id_bireport_pbi_report_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biaccess',
            options={'default_permissions': (), 'ordering': ['-accessed_at'], 'permissions': [('view_bi', 'Lista geral BI'), ('edit_bi', 'Editar BI'), ('view_access', 'Visualizar Acessos'), ('permission_report', 'Relatório de permissões de BI'), ('refresh_bi', 'Atualizar BI')], 'verbose_name': 'Acesso a BI', 'verbose_name_plural': 'Acessos a BI'},
        ),
    ]
