# Generated by Django 5.1.1 on 2024-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_ad_user',
            field=models.BooleanField(default=False),
        ),
    ]
