# Generated by Django 5.1.1 on 2024-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='meu_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
