# Generated by Django 5.1.1 on 2024-10-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_meu_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='meu_checkbox',
            new_name='gerente',
        ),
    ]
