# Generated by Django 5.1.1 on 2024-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
    ]
