# Generated by Django 5.1.1 on 2024-10-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_is_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_approver',
        ),
    ]
