# Generated by Django 5.1.2 on 2024-10-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0008_grupo_permissions_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissões'),
        ),
    ]
