# Generated by Django 5.1.2 on 2024-10-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_options_remove_usuario_gerente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_user.jpg', upload_to='profile_photos/'),
        ),
    ]
