# Generated by Django 5.1.2 on 2024-11-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_options_alter_usuario_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_list_user', 'Pode ver lista de Usuário')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
