# Generated by Django 5.1.2 on 2024-11-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_list_user', 'Lista de Usuário'), ('can_edit_user', 'Editar Usuário'), ('can_add_user', 'Cadastra Usuário'), ('change_permission', 'Liberar Permissões')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
