# Generated by Django 5.1.2 on 2024-11-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_list_user', 'Lista de Usuário'), ('can_edit_user', 'Editar Usuário'), ('can_add_user', 'Cadastra Usuário'), ('can_import_user', 'Importar Usuário'), ('change_permission', 'Liberar Permissões'), ('can_view_list_group', 'Lista de Grupos'), ('can_edit_group', 'Editar Grupo'), ('can_add_group', 'Cadastra Grupo'), ('can_delete_group', 'Excluir Grupo')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
