# Generated by Django 5.1.2 on 2024-11-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0024_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('list_user', 'Lista de Usuários'), ('can_add_user', 'Cadastra Usuário'), ('can_import_user', 'Importar Usuário '), ('can_edit_user', 'Editar Usuário'), ('change_permission', 'Liberar Permissões'), ('can_view_list_group', 'Lista de Grupos'), ('can_add_group', 'Cadastra Grupo'), ('can_edit_group', 'Editar Grupo'), ('can_delete_group', 'Excluir Grupo')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='auth.permission'),
        ),
    ]
