# Generated by Django 5.1.2 on 2024-11-19 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0025_alter_usuario_options_alter_grupo_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('list_user', 'Lista de Usuários'), ('can_add_user', 'Cadastra Usuário'), ('can_import_user', 'Importar Usuário'), ('can_edit_user', 'Editar Usuário'), ('change_permission', 'Liberar Permissões'), ('can_view_list_group', 'Lista de Grupos'), ('can_add_group', 'Cadastra Grupo'), ('can_edit_group', 'Editar Grupo'), ('can_delete_group', 'Excluir Grupo')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='participantes',
            field=models.ManyToManyField(related_name='grupos', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='auth.permission', verbose_name='Permissões'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', to='usuarios.grupo', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
