# Generated by Django 5.1.2 on 2024-11-19 19:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0027_alter_grupo_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('list_user', 'Pode listar usuários'), ('can_add_user', 'Pode cadastrar usuário'), ('can_import_user', 'Pode importar usuário'), ('can_edit_user', 'Pode editar usuário'), ('change_permission', 'Pode liberar permissões'), ('can_view_list_group', 'Pode listar grupos'), ('can_add_group', 'Pode cadastrar grupo'), ('can_edit_group', 'Pode editar grupo'), ('can_delete_group', 'Pode excluir grupo')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
