# Generated by Django 5.1.2 on 2024-11-19 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0028_alter_usuario_options_delete_grupo_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('list_user', 'Lista de Usuários'), ('can_add_user', 'Cadastra Usuário'), ('can_import_user', 'Importar Usuário '), ('can_edit_user', 'Editar Usuário'), ('change_permission', 'Liberar Permissões'), ('can_view_list_group', 'Lista de Grupos'), ('can_add_group', 'Cadastra Grupo'), ('can_edit_group', 'Editar Grupo'), ('can_delete_group', 'Excluir Grupo')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('participantes', models.ManyToManyField(related_name='grupos', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
    ]
