# Generated by Django 5.1.2 on 2025-07-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('list_user', 'Lista de Usuários'), ('can_add_user', 'Cadastra Usuário'), ('can_import_user', 'Importar Usuário'), ('can_edit_user', 'Editar Usuário'), ('change_permission', 'Liberar Permissões'), ('can_duplica_acesso', 'Duplicar Acesso'), ('can_view_list_group', 'Lista de Grupos'), ('can_add_group', 'Cadastra Grupo'), ('can_edit_group', 'Editar Grupo'), ('can_delete_group', 'Excluir Grupo'), ('permission_report', 'Relatório de permissões de Usuários')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
