# Generated by Django 5.1.2 on 2025-04-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ia.chatmessage'),
        ),
    ]
