# Generated by Django 5.1.2 on 2025-04-24 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_chatattachment_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Tokens enviados para a API.')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Tokens recebidos (gerados) pela API.')),
                ('image_count', models.PositiveSmallIntegerField(default=0, help_text='Número de imagens enviadas na requisição.')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, help_text='Custo estimado desta chamada à API em USD (ou sua moeda base).', max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ai_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_log_entry', to='ia.chatmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
