# Generated by Django 5.1.2 on 2025-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='estimated_cost_brl',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Custo estimado (BRL) desta chamada.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Custo estimado (USD) desta chamada.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='image_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de imagens na requisição.'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Tokens recebidos pela API.'),
        ),
    ]
