# Generated by Django 5.1.2 on 2025-04-24 14:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_apiusagelog_estimated_cost_brl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_all_api_costs', 'Pode visualizar custos de API de todos os usuários')], 'verbose_name': 'Log de Uso da API', 'verbose_name_plural': 'Logs de Uso da API'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversa IA', 'verbose_name_plural': 'Conversas IA'},
        ),
        migrations.AlterModelOptions(
            name='chatattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Anexo IA', 'verbose_name_plural': 'Anexos IA'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Mensagem IA', 'verbose_name_plural': 'Mensagens IA'},
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='ai_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_log_entry', to='ia.chatmessage', verbose_name='Mensagem IA Associada'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Custo estimado (USD) desta chamada, baseado nos tokens/imagens.', max_digits=10, verbose_name='Custo Estimado (USD)'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='estimated_cost_brl',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Custo estimado (BRL) convertido a partir do USD.', max_digits=12, verbose_name='Custo Estimado (BRL)'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='image_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de imagens enviadas na requisição.', verbose_name='Qtd. Imagens'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Tokens enviados para a API (prompt + histórico).', verbose_name='Tokens de Entrada'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Modelo Utilizado'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Tokens recebidos da API (resposta gerada).', verbose_name='Tokens de Saída'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp da Requisição'),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Nova Conversa', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to='ia.chat', verbose_name='Conversa (Anexo)'),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='file',
            field=models.FileField(upload_to='chat_attachments/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ia.chatmessage', verbose_name='Mensagem Associada'),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.chat', verbose_name='Conversa'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Usuário'), ('ai', 'IA')], max_length=50, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(verbose_name='Texto da Mensagem'),
        ),
    ]
