# Generated by Django 5.1.2 on 2025-04-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0005_alter_apiusagelog_options_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_all_api_costs', 'Pode visualizar custos de API de todos os usuários'), ('chat_pag', 'Chat IA'), ('cost_monitor', 'Custos IA')], 'verbose_name': 'Log de Uso da API', 'verbose_name_plural': 'Logs de Uso da API'},
        ),
    ]
