# Generated by Django 5.1.2 on 2025-04-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_alter_apiusagelog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_all_api_costs', 'Pode visualizar custos de API de todos os usuários'), ('chat_pag', 'Chat IA'), ('cost_monitor', 'Custos IA'), ('model_2.5_pro', 'Modelo mais caro Gemini 2.5 Pro')], 'verbose_name': 'Log de Uso da API', 'verbose_name_plural': 'Logs de Uso da API'},
        ),
    ]
