# Generated by Django 5.1.2 on 2025-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0008_alter_apiusagelog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active_spreadsheet_attachment_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='active_spreadsheet_columns_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
