# Generated by Django 5.1.2 on 2025-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0009_chat_active_spreadsheet_attachment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active_spreadsheet_original_columns_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
