# Generated by Django 5.1.2 on 2025-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0010_chat_active_spreadsheet_original_columns_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
