# Generated by Django 5.1.2 on 2025-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0012_remove_chat_metadata_chatattachment_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatattachment',
            name='metadata',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
