# Generated by Django 5.1.2 on 2025-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0013_remove_chatattachment_metadata_chatmessage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='assistant_thread_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
