# Generated by Django 5.1.2 on 2025-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0014_chat_assistant_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='metadata',
            field=models.JSONField(blank=True, help_text="Info auxiliar (ex.: {'oa_file_id': 'file_abc123'})", null=True),
        ),
    ]
