# Generated by Django 5.1.2 on 2025-06-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0016_alter_apiusagelog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_all_api_costs', 'Pode visualizar custos de API de todos os usuários'), ('chat_pag', 'Chat IA'), ('cost_monitor', 'Custos IA'), ('model_2.5_pro', 'Modelo mais caro Gemini 2.5 Pro'), ('model_1.5_pro', 'Modelo  Gemini 1.5 Pro'), ('rotoplastyc_ia', 'Modelo  Rotoplastyc IA para documentos'), ('gpt_4o_mini', 'Modelo GPT-4o Mini'), ('gpt_4o', 'Modelo GPT-4o')], 'verbose_name': 'Log de Uso da API', 'verbose_name_plural': 'Logs de Uso da API'},
        ),
    ]
