# Generated by Django 5.1.2 on 2025-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altforce_sync', '0003_recreate_budget_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='id_tem',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Técnico do Item'),
        ),
        migrations.AddField(
            model_name='apiorcamentoopcional',
            name='id_tem',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Técnico do Item'),
        ),
        migrations.AddField(
            model_name='apiorcamentoproduto',
            name='id_tem',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Técnico do Item'),
        ),
        migrations.AddIndex(
            model_name='apiorcamentoobservacao',
            index=models.Index(fields=['id_tem'], name='dApiOrcamen_id_tem_d41d55_idx'),
        ),
        migrations.AddIndex(
            model_name='apiorcamentoopcional',
            index=models.Index(fields=['id_tem'], name='dApiOrcamen_id_tem_017b51_idx'),
        ),
        migrations.AddIndex(
            model_name='apiorcamentoproduto',
            index=models.Index(fields=['id_tem'], name='dApiOrcamen_id_tem_11cb11_idx'),
        ),
    ]
