# Generated by Django 5.1.2 on 2025-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altforce_sync', '0004_apiorcamentoobservacao_id_tem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apilead',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apileadproduto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='apiorcamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apiorcamentoobservacao',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='apiorcamentoopcional',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='apiorcamentoproduto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='apipedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apipedidoorcamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apipedidoproduto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apipedidotecnicon',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='apiorcamentoobservacao',
            name='uq_dapiorcamentosobservacoes_orcamento_item_line',
        ),
        migrations.RemoveConstraint(
            model_name='apiorcamentoopcional',
            name='uq_dapiorcamentosopcionais_orcamento_item',
        ),
        migrations.RemoveConstraint(
            model_name='apiorcamentoproduto',
            name='uq_dapiorcamentosproduto_orcamento_item',
        ),
        migrations.RemoveIndex(
            model_name='apiorcamentoobservacao',
            name='dApiOrcamen_altforc_d5d44b_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiorcamentoobservacao',
            name='dApiOrcamen_id_tem_d41d55_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiorcamentoopcional',
            name='dApiOrcamen_altforc_1314a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiorcamentoopcional',
            name='dApiOrcamen_id_tem_017b51_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiorcamentoproduto',
            name='dApiOrcamen_altforc_af314e_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiorcamentoproduto',
            name='dApiOrcamen_id_tem_11cb11_idx',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoobservacao',
            name='description_id',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoobservacao',
            name='description_value',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoobservacao',
            name='id_tem',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoobservacao',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoobservacao',
            name='line_index',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoopcional',
            name='id_tem',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoopcional',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoproduto',
            name='id_tem',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoproduto',
            name='item_id',
        ),
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='descriptions_values',
            field=models.JSONField(blank=True, null=True, verbose_name='Observações (values)'),
        ),
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='apiorcamentoopcional',
            name='product_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='apiorcamentoproduto',
            name='product_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Product ID'),
        ),
        migrations.AddIndex(
            model_name='apiorcamentoobservacao',
            index=models.Index(fields=['altforce_id', 'product_id'], name='dApiOrcamen_altforc_74600a_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiorcamentoobservacao',
            constraint=models.UniqueConstraint(fields=('orcamento', 'product_id'), name='uq_dapiorcamentosobservacoes_orcamento_product'),
        ),
        migrations.AddConstraint(
            model_name='apiorcamentoopcional',
            constraint=models.UniqueConstraint(fields=('orcamento', 'product_id'), name='uq_dapiorcamentosopcionais_orcamento_product'),
        ),
        migrations.AddConstraint(
            model_name='apiorcamentoproduto',
            constraint=models.UniqueConstraint(fields=('orcamento', 'product_id'), name='uq_dapiorcamentosproduto_orcamento_product'),
        ),
    ]
