# Generated by Django 5.1.2 on 2025-10-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altforce_sync', '0005_alter_apicliente_options_alter_apilead_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apiorcamentoobservacao',
            name='uq_dapiorcamentosobservacoes_orcamento_product',
        ),
        migrations.RemoveField(
            model_name='apiorcamentoobservacao',
            name='descriptions_values',
        ),
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='description_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Description ID'),
        ),
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_set', to='altforce_sync.apiorcamentoproduto'),
        ),
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='ord',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='apiorcamentoobservacao',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='apiorcamentoopcional',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcionais_set', to='altforce_sync.apiorcamentoproduto'),
        ),
        migrations.AlterField(
            model_name='apiorcamentoobservacao',
            name='product_id',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='Product ID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='apiorcamentoobservacao',
            index=models.Index(fields=['item'], name='dApiOrcamen_item_id_7868ab_idx'),
        ),
        migrations.AddIndex(
            model_name='apiorcamentoopcional',
            index=models.Index(fields=['item'], name='dApiOrcamen_item_id_42af45_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiorcamentoobservacao',
            constraint=models.UniqueConstraint(fields=('orcamento', 'product_id', 'ord'), name='uq_dapiorcamentosobservacoes_orc_prod_ord'),
        ),
    ]
