# Generated by Django 5.1.2 on 2025-09-03 10:44

import django.db.models.deletion
import sqlhub.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('engine', models.CharField(choices=[('firebird', 'Firebird'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB'), ('mssql', 'SQL Server')], max_length=20)),
                ('host', models.CharField(blank=True, default='', max_length=200)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('database', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('password', sqlhub.fields.EncryptedTextField()),
                ('options', models.JSONField(blank=True, default=dict)),
                ('read_only', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dbconns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sql_text', models.TextField(help_text="Apenas SELECT. WHERE/ORDER BY permitidos. Evite ';'.")),
                ('default_limit', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='sqlhub.dbconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('connection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_hash', models.CharField(db_index=True, max_length=64)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caches', to='sqlhub.savedquery')),
            ],
            options={
                'indexes': [models.Index(fields=['query', 'params_hash', 'expires_at'], name='sqlhub_quer_query_i_95dc67_idx')],
            },
        ),
    ]
