# Generated by hand – renomeia as tabelas para PT-BR
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sqlhub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dbconnection",
            table="sqlhub_conexao",
        ),
        migrations.AlterModelTable(
            name="savedquery",
            table="sqlhub_consulta",
        ),
        migrations.AlterModelTable(
            name="querycache",
            table="sqlhub_cache_consulta",
        ),
        # Só para registrar verbose_name/plural no migration history (opcional)
        migrations.AlterModelOptions(
            name="dbconnection",
            options={
                "verbose_name": "Conexão de banco",
                "verbose_name_plural": "Conexões de banco",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="savedquery",
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ("connection__name", "name"),
                "unique_together": {("connection", "name")},
            },
        ),
        migrations.AlterModelOptions(
            name="querycache",
            options={
                "verbose_name": "Cache de consulta",
                "verbose_name_plural": "Caches de consulta",
            },
        ),
    ]
