# Generated by Django 5.1.2 on 2025-09-05 11:04

import django.db.models.deletion
import sqlhub.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0003_rename_sqlhub_quer_query_i_95dc67_idx_sqlhub_cach_query_i_448696_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='querycache',
            new_name='sqlhub_cach_consult_6d6566_idx',
            old_name='sqlhub_cach_query_i_448696_idx',
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='created_by',
            field=models.ForeignKey(db_column='criado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='dbconns', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='database',
            field=models.CharField(blank=True, db_column='banco_servico', default='', help_text='Para Firebird use o caminho completo do .FDB. Para SQL Server pode deixar vazio.', max_length=300, verbose_name='Banco/Serviço'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='engine',
            field=models.CharField(choices=[('firebird', 'Firebird'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB'), ('mssql', 'SQL Server')], db_column='tipo_banco', max_length=20, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='host',
            field=models.CharField(blank=True, db_column='host', default='', max_length=200, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='name',
            field=models.CharField(db_column='nome', max_length=80, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='options',
            field=models.JSONField(blank=True, db_column='opcoes', default=dict, help_text='Ex.: {"odbc_driver": "ODBC Driver 18 for SQL Server", "charset": "UTF8"}', verbose_name='Opções'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='password',
            field=sqlhub.fields.EncryptedTextField(db_column='senha', verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='port',
            field=models.PositiveIntegerField(blank=True, db_column='porta', null=True, verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='read_only',
            field=models.BooleanField(db_column='somente_leitura', default=True, verbose_name='Somente leitura'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='username',
            field=models.CharField(db_column='usuario', max_length=200, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='querycache',
            name='columns',
            field=models.JSONField(blank=True, db_column='colunas', default=list, verbose_name='Colunas'),
        ),
        migrations.AlterField(
            model_name='querycache',
            name='expires_at',
            field=models.DateTimeField(db_column='expira_em', db_index=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='querycache',
            name='params_hash',
            field=models.CharField(db_column='hash_parametros', db_index=True, max_length=64, verbose_name='Hash dos parâmetros'),
        ),
        migrations.AlterField(
            model_name='querycache',
            name='query',
            field=models.ForeignKey(db_column='consulta_id', on_delete=django.db.models.deletion.CASCADE, related_name='caches', to='sqlhub.savedquery', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='querycache',
            name='rows',
            field=models.JSONField(blank=True, db_column='linhas', default=list, verbose_name='Linhas'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='connection',
            field=models.ForeignKey(db_column='conexao_id', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='sqlhub.dbconnection', verbose_name='Conexão'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='created_by',
            field=models.ForeignKey(db_column='criada_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='queries_created', to=settings.AUTH_USER_MODEL, verbose_name='Criada por'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='default_limit',
            field=models.PositiveIntegerField(db_column='limite_padrao', default=1000, verbose_name='Limite padrão'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='is_active',
            field=models.BooleanField(db_column='ativa', default=True, verbose_name='Ativa?'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='meta',
            field=models.JSONField(blank=True, db_column='metadados', default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='name',
            field=models.CharField(db_column='nome', max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='sql_text',
            field=models.TextField(db_column='sql_texto', help_text="Apenas SELECT. WHERE/ORDER BY permitidos. Evite ';'.", verbose_name='SQL (somente SELECT)'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='atualizada_em', verbose_name='Atualizada em'),
        ),
    ]
