# Generated by Django 5.1.2 on 2025-09-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0004_rename_sqlhub_cach_query_i_448696_idx_sqlhub_cach_consult_6d6566_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'default_permissions': (), 'ordering': ('name',), 'permissions': [('test_connection', 'Pode testar conexão')], 'verbose_name': 'Conexão de banco', 'verbose_name_plural': 'Conexões de banco'},
        ),
        migrations.AlterModelOptions(
            name='savedquery',
            options={'ordering': ('connection__name', 'name'), 'permissions': [('execute_savedquery', 'Pode executar consultas'), ('export_savedquery', 'Pode exportar resultados (CSV)'), ('adhoc_savedquery', 'Pode executar consultas ad-hoc')], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelTable(
            name='dbconnection',
            table=None,
        ),
    ]
