# Generated by Django 5.1.2 on 2025-09-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0005_alter_dbconnection_options_alter_savedquery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'default_permissions': (), 'ordering': ('name',), 'permissions': [('sqlhub', 'Pode usar o SQLHub')], 'verbose_name': 'Conexão de banco', 'verbose_name_plural': 'Conexões de banco'},
        ),
    ]
