# Generated by Django 5.1.2 on 2025-09-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0006_alter_dbconnection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('test_connection', 'Pode testar conexão')], 'verbose_name': 'Conexão de banco', 'verbose_name_plural': 'Conexões de banco'},
        ),
    ]
