# Generated by Django 5.1.2 on 2025-09-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0007_alter_dbconnection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedquery',
            options={'default_permissions': (), 'ordering': ('connection__name', 'name'), 'permissions': [('execute_savedquery', 'Pode executar consultas'), ('export_savedquery', 'Pode exportar resultados (CSV)'), ('adhoc_savedquery', 'Pode executar consultas ad-hoc')], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
