# Generated by Django 5.1.2 on 2025-09-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0008_alter_savedquery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('view_dbconnection', 'Pode visualizar conexões'), ('add_dbconnection', 'Pode criar conexões'), ('change_dbconnection', 'Pode editar conexões'), ('delete_dbconnection', 'Pode excluir conexões'), ('test_connection', 'Pode testar conexão')], 'verbose_name': 'Conexão de banco', 'verbose_name_plural': 'Conexões de banco'},
        ),
        migrations.AlterModelOptions(
            name='savedquery',
            options={'default_permissions': (), 'ordering': ('connection__name', 'name'), 'permissions': [('view_savedquery', 'Pode visualizar consultas'), ('add_savedquery', 'Pode criar consultas'), ('change_savedquery', 'Pode editar consultas'), ('delete_savedquery', 'Pode excluir consultas'), ('execute_savedquery', 'Pode executar consultas'), ('export_savedquery', 'Pode exportar resultados (CSV)'), ('adhoc_savedquery', 'Pode executar consultas ad-hoc')], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
