# Generated by Django 5.1.2 on 2025-09-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0009_alter_dbconnection_options_alter_savedquery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querycache',
            options={'default_permissions': (), 'permissions': [], 'verbose_name': 'Cache de consulta', 'verbose_name_plural': 'Caches de consulta'},
        ),
    ]
