# Generated by Django 5.1.2 on 2025-09-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlhub', '0010_alter_querycache_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconnection',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('sqglgub', 'Pode acessar o SQLHub')], 'verbose_name': 'Conexão de banco', 'verbose_name_plural': 'Conexões de banco'},
        ),
        migrations.AlterModelOptions(
            name='savedquery',
            options={'default_permissions': (), 'ordering': ('connection__name', 'name'), 'permissions': [], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
