# Generated by Django 5.1.2 on 2024-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
